version: '3.1'
services:
        apache-hop:
                image: apache/hop
                container_name: apache-hop_1
                ports:
                        - 8080:8080
                environment: 
                 HOP_SERVER_USER: admin
                 HOP_SERVER_PASS: pass

        apache-hop-web:
                image: apache/hop-web
                container_name: apache-hop_web_1
                ports:
                        - 8081:8080
                environment: 
                 HOP_SERVER_USER: admin
                 HOP_SERVER_PASS: pass
networks:
        compose-network:
                driver: bridge